import './style.css'
//import './base/app'
//import './base/tiposDatos'
//import './base/booleans'
//import './base/number'
//import './base/string'
//import './base/any'
//import './base/arrays'
//import './base/tuplas'
//import './base/enums'
//import './base/void'
//mport './base/never'
//import './base/nullYundefiend.ts'
//import './func/funciones'
//import './func/args-required'
///import './func/args-opcional'
//import './func/args-default'
//import './func/args-rests'
//import './func/function-type'
//import './objects/objetos'
//import './objects/types'
//import './objects/union-types'
//import './es6/letvar'
//import './es6/destObjets'

//import './es6/destArreglo'
//import './es6/forOf'
//import './classes/clases'
//import './classes/herencia'
//import './classes/getYset'
//import './classes/abstract'
//import './classes/private-constructor'
//import './interfaces/basicas'
//import './interfaces/complejas'
//import './interfaces/clases'
//import './interfaces/funciones'
//import './namespaces/validation'
//import './classes/index'
//import './generics/index'

//import './generics/indexPokemon'

import './decoradores/indexPokemon'
    